clojure/clojure-site

content/community/contributing_site.adoc
Added instructions to update the fork before working on a large change.
=> Keeping contributor's fork up-to-date

content/community/contributing_site.adoc
Adapted the text according to suggestions given by @danielcompton and @arrdem . Also modified the command `git co -b <branchname>` to `git checkout -b <branchname>` to make it more readable.
=> Changes according to suggestions

content/community/books.adoc
Added books to book page. 
Please support these fine books about Clojure.
=> Patch 1 - updated book list

content/guides/comparators.adoc, content/index.adoc
Hey @puredanger, finally able to get to it.
https://github.com/clojure/clojure-site/issues/15
=> add comparators guide

content/community/contributors.csv
this corrects my github username
=> correct github username

content/community/contributors.csv
add my name together with Baishampayan Ghose's
=> Add 2 github names

content/community/contributors.csv
Thank you for all your hard work on the new site! Looks great.
=> Correct spelling of contributor, add Github user

content/guides/reader_conditionals.adoc
I've converted my [blog post](http://danielcompton.net/2015/06/10/clojure-reader-conditionals-by-example) into a guide, and tweaked the tone of the article.
I expect there will be further changes to wording, style, e.t.c. required, I'm opening this PR for feedback and discussion.
In particular, I'm not quite sure what the right place for the link to the guide from the Reader reference page is. I'm also not sure if we want to encourage the 'neat trick' with namespaces that I show Vesa Karvonen used?
Fixes #8
=> Add Reader Conditionals guide

content/api/api.adoc
See https://github.com/clojure/clojure-site/issues/47
Signed-off-by: ZhiFeng Hu <hufeng1987@gmail.com>
=> Enhance libraries list #47

content/api/cheatsheet.html
Also updated URLs for new clojure.org
=> Update cheatsheet to v35, with new vars and doc strings for Clojure 1.8

content/guides/guides.adoc, content/guides/threading_macros.adoc
Add a guide to all threading macros in clojure.core
All comments/criticism welcome
=> Add guide to threading macros

content/about/spec.adoc
My intuition as a native english speaker suggests this word should go there.
=> Add a word

content/guides/spec.adoc
=> Small typo

content/guides/spec.adoc
Hi - Not sure if this bit of text was meant to be deleted or if there is other missing text that was meant to accompany it.
=> unwanted text fragment?

content/guides/spec.adoc
First-time contributor, please let me know if I've made any mistakes in this process.
I filled out a Clojure CA in person at clojure/west in Portland back in 2013.
=> Fix a small typo in the spec guide

content/events/2016/clojurebridge_krakow.adoc
Another ClojureBridge workshop has been scheduled, the first chapter in Poland!
=> This commit adds ClojureBridge Kraków, Poland chapter

content/events/2017/clojurex-london.adoc
Created an event page for the ClojureX London 2017 conference
=> ClojureX London 2017 event

content/events/2017/clojureremote.adoc
=> Add clojureremote event. Fix #155

content/community/companies.adoc
I also have sent an email directly for this, but also created a PR in hope that it will make life easier for @puredanger .
=> Add Cybozu Startups to the list companies

content/community/companies.adoc
Small nitpick, which makes the list more harmonious
=> Exoscale capitalization

content/events/2017/clojutre.adoc
Sorry, I had a typo on the start date.
=> Fix type on Clojutre start date

content/reference/compilation.adoc
=> Descrease -> decrease

content/guides/spec.adoc
This fixes two misspellings of "satisfied" and "occurrence." Thanks for spec! ❤️
=> Fix two typos

content/guides/guides.adoc, content/guides/weird_characters.adoc, content/reference/reader.adoc
- transcribe https://yobriefca.se/blog/2014/05/19/the-weird-and-wonderful-characters-of-clojure/
- add some anchors for cross-reference
- add guide to guides
=> Add The Weird and Wonderful Characters of Clojure, fixes #181

content/guides/weird_characters.adoc
=> [docs] Add missing # from var quote example

content/events/2017/clojurebridge-sanfrancisco.adoc
Fix a typo, last change, I promise :(.
=> update sf clojurebridge post language

content/community/companies.csv
This seemed like the right place to add it, but let me know if I've done anything wrong.
=> Add Deps to companies list

content/events/2018/clojutre.adoc
=> Add ClojuTRE 2018

content/community/training.adoc
Helps Enterprises find Clojure Training courses for their teams.
=> adds training page see issue #246

content/community/resources.adoc
=> Add Visual Studio Code to tools

content/events/2018/clojurex.adoc
Description of the ClojureX conference in London in December 2018
- [ x] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [ x] Have you signed the Clojure Contributor Agreement?
- [ x] Have you verified your asciidoc markup is correct?
=> ClojureX conference 2018

content/community/user_groups.adoc
- [x ] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [ x] Have you signed the Clojure Contributor Agreement?
- [x ] Have you verified your asciidoc markup is correct?
This is a first shot. Basically copied from confluence, with some small editorial changes.
I have not done any verification of links etc.
=> [Fix #260] Move user groups from confluence

content/guides/repl/data_visualization_at_the_repl.adoc
Preview: https://5ad1e723fdd72a77a2a8c4f4--clojure-site-preview-vvvvalvalval.netlify.com/guides/repl/data_visualization_at_the_repl#_dealing_with_mysterious_values_advanced
=> Added a 'Dealing with mysterious values' section to REPL guide

content/guides/destructuring.adoc
=> Update namespaced keys section of destructuring guide #265

content/reference/reducers.adoc, content/reference/refs.adoc
=> Fix broken markup

content/guides/faq.adoc
=> Add FAQ entry about standalone Clojure scripts

content/reference/transducers.adoc
=> Link "see also" to FAQ section

content/reference/compilation.adoc
This seems like the way it was intended to be written.
=> Indent these bullet points

content/guides/weird_characters.adoc, content/reference/reader.adoc
- [yes] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [yes] Have you signed the Clojure Contributor Agreement?
- [yes] Have you verified your asciidoc markup is correct?
=> Add symbolic values to reader reference and weird character guide

content/community/books.adoc
=> A new Clojure book about using Java libraries

content/api/api.adoc, content/community/resources.adoc
=> Fix grimoire links.

content/guides/learn/functions.adoc
=> Change "not" to "no" in part one of "Test your knowledge"

content/community/books.adoc
=> Add Clojure Polymorphism

content/community/companies.csv
Fixed broken link to our company website.
=> Fixed URL for our company DocSolver

content/guides/weird_characters.adoc
=> Removed incorrect #= examples

content/api/api.adoc
=> Add cljdoc to list of other API-related resources

content/guides/faq.adoc
=> Docs: Fix grammar

content/community/user_groups.adoc
=> HTTPS all the Meetup.com

content/community/user_groups.adoc
=> Add Bulgarian user group

content/community/devchangelog.adoc, content/guides/faq.adoc, content/reference/compilation.adoc, content/reference/evaluation.adoc, content/reference/repl_and_main.adoc
=> Add a missing word and fix a handful of earmuffs

content/community/training.adoc
- [x ] Have you verified your asciidoc markup is correct?
=> Added Mark Engelberg to training document

content/guides/weird_characters.adoc
=> Add example using alias for map keyword namespace

content/community/companies.adoc
Otherwise, the instructions say to email Alex, so people might assume they can't do a PR for this page, or need his approval first.
=> Add bit on Companies page about updating by PR with link to the site's repo

content/guides/deps_and_cli.adoc
While answering a [stack overflow question
](https://stackoverflow.com/questions/53171063/clojure-is-it-possible-to-inherit-state-of-class-defined-with-gen-class/53179570#53179570) I figured out how to achieve this with Clojure deps and cli. I thought this would be a good thing to make into a guide.
=> Added guide for AOT with deps and cli

content/guides/equality.adoc
- [yes] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [yes] Have you signed the Clojure Contributor Agreement?
- [no, but would be happy to if I learn how to do so] Have you verified your asciidoc markup is correct?
=> Add new guide on Clojure equality

content/community/resources.adoc
=> List couple of more conferences in Europe

content/community/resources.adoc
=> Add Clojurians Zulip

content/events/2019/clojurenorth.adoc
Added a tweak to the Clojure/north page, and added the tickets link now that it's live.
=> Clojurenorth update

content/guides/repl/enhancing_your_repl_workflow.adoc
=> Update some nREPL references

content/community/companies.adoc
=> Add company

content/guides/comparators.adoc
- [yes] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [yes] Have you signed the Clojure Contributor Agreement?
- [yes] Have you verified your asciidoc markup is correct?
=> Updates to comparators guide

content/community/companies.adoc
=> adding CROWD to companies that use clojure :smile:

content/community/contributors.csv
Fix incorrect GitHub username. My username is brandonbloom, not bbloom.
=> Fix incorrect username in contributors.csv

content/community/training.adoc
=> Add learnreagent and learnreframe

content/community/companies.adoc
=> Update link to WorksHub

content/community/user_groups.adoc
=> Clojure Toronto now has a new website

content/community/resources.adoc
=> Updated the link of Clojure User Groups from Confluence to the website

content/events/2019/clojutre.adoc
=> Add ClojuTRE 2019

content/guides/learn/flow.adoc
=> Add missing REPL prompt in Flow Control docs

content/reference/vars.adoc
=> Fix the link to internting section in Vars documentation

content/about/rationale.adoc
=> Fix markup typo

content/guides/comparators.adoc
- [y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [y] Have you signed the Clojure Contributor Agreement?
- [y] Have you verified your asciidoc markup is correct?
=> Add notes to comparators guide on avoiding NaN

content/community/training.adoc
=> Training: Add Klipse Technologies

content/dev/contributors.csv
=> Fix contributor name

content/news/2014/08/06/transducers-are-coming.adoc
=> Fix link to reducers page

content/reference/java_interop.adoc
=> java_interop: how to attach java annotations

content/community/contrib_howto.adoc
=> Update references to Hudson

content/guides/guides.adoc, content/guides/test_check/beginner.adoc
There are a few formatting issues that I can't figure out:
- the title formatting doesn't work
- some of the #() inline code examples don't work (but not all???)
- the backticked level-5 headers don't look like headers
=> Add beginner guide to test.check

content/community/companies.adoc
=> Add 1st1.dev

content/guides/learn/functions.adoc
Use "parameter" not "argument" to describe function parameters.
- [*] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [*] Have you signed the Clojure Contributor Agreement?
- [*] Have you verified your asciidoc markup is correct?
=> Update functions.adoc wording

content/dev/dev.adoc
=> Grammar fix: interesting => interested

content/community/companies.adoc
- [ X] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [X ] Have you verified your asciidoc markup is correct?
=> Company Pisano added to the companies.adoc

content/community/companies.adoc
Adds www.squarevenue.com to list, a full stack clojure app :) ❤️ 
* I didn't go through the entire process of becoming a contributor for such a small PR - if I need to, I can just contact the email address present for the same outcome I just thought I'd do the leg work.
Thanks in advance
=> Add SquareVenue to companies list

content/community/resources.adoc
=> Add Clojure podcasts under community resources

content/community/resources.adoc
=> Add (dosync radio) to the list of podcasts

content/community/contrib_libs.adoc
=> Switch java.data maintainer to me, mark as Active

content/guides/learn/answers.adoc
=> Fixed a grammatical & syntactical mistake

content/events/2019/reclojure.adoc
=> Update re:Clojure conference information

content/events/2019/reclojure.adoc
=> Update re:Clojure conference information - remove typo

content/events/2020/inclojure.adoc
Yes, the commit was pushed by `adityaathalye` listed here: https://clojure.org/dev/contributors
=> Add IN/Clojure 2020 event info (Feb 14-15, Pune, IN)

content/reference/deps_and_cli.adoc
https://clojure.atlassian.net/browse/TDEPS-140
=> Document how to add HTTP headers to Maven (TDEPS-140)

content/guides/learn/syntax.adoc
make punctutation -> punctuation
=> fix smol spelling error

content/events/2020/clojurenorth.adoc
=> Add Clojure/north 2020 event

content/community/companies.adoc
We are using Clojure(+Script) for the backend + frontend of our app (https://app.vetd.com).
Thanks!
=> add Vetd to companies list

content/events/2020/clojurebridge.adoc
=> Add in ClojureBridge Event Page

content/events/2020/clojurebridge.adoc
=> Update Link and new Logo

content/guides/learn/answers.adoc
=> code example was incorrect wrong number of bracket

content/reference/deps_and_cli.adoc
to make it easier to find tools that work with and extend tools-deps. (I had to ask in Slack to find the page so it would be useful to have a link to it from here, where everybody comes first.)
=> deps and CLI: Link to the wiki/Tools page

content/community/user_groups.adoc
=> Added DFW Southlake clojure mid-cities meetup

content/community/companies.adoc
We are using Clojure(+Script) for the backend + frontend of our app
Thanks!
=> Add Lumanu company to the community page

content/reference/reader.adoc
=> Add mention of hexadecimal number literals

content/community/companies.adoc
"Akvo.org" and "Akvo foundation" are the same entity.
=> Duplicate entry

content/reference/datatypes.adoc
=> Fix grammatical typo

content/community/companies.adoc
hi we write parens to find vulns :wave:
=> Add Latacora to list of Clojure-using companies

content/community/companies.adoc
=> Add Commsor to companies list

content/community/resources.adoc
Two resource entries, one for community and one for video & presentations
sections.
---
=> Community resources - practicalli

content/community/resources.adoc
Add Neovim + Conjure to Clojure Tools (in Community/Resources)
=> Add Neovim + Conjure

content/guides/faq.adoc
Based on a discussion in the Slack #beginners channel, Alex suggested I propose this addition.
=> Add FAQ about ? and ! in symbols

content/reference/deps_and_cli.adoc
=> Fix grammar

content/community/companies.adoc
=> Add BGPworks to list of clojure-using companies.

content/community/companies.adoc
=> Add Makimo to companies.adoc

content/reference/vars.adoc
=> Fix links in content/reference/vars.adoc

content/community/companies.adoc
=> Add company luminaremed.com

content/guides/repl/annex_community_resources.adoc, content/guides/repl/data_visualization_at_the_repl.adoc, content/guides/repl/enhancing_your_repl_workflow.adoc
=> Add a few recent recommendations to the REPL guide.

content/guides/weird_characters.adoc, content/reference/reader.adoc
=> Added few minor details in example

content/reference/special_forms.adoc
=> Shored up the language around destructuring and added a section on keyword arguments.

content/reference/java_interop.adoc
=> Escape unwanted AsciiDoc replacement.

content/community/resources.adoc
=> Add new podcast "Lost in Lambduhhs" to resources

content/guides/deps_and_cli.adoc
=> Link to 1.10.3 changelog

content/reference/deps_and_cli.adoc
- [/] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [/] Have you signed the Clojure Contributor Agreement?
- [/] Have you verified your asciidoc markup is correct?
=> added section about trailing map

content/reference/deps_and_cli.adoc
=> Information about comping fns with CLI

content/guides/repl/annex_community_resources.adoc
Online meetup talk about Clojure's REPL with a live, 40-minute demo.
=> Add Sean Corfield's REPL-Driven Development talk

content/community/companies.adoc
- [+] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [-] Have you signed the Clojure Contributor Agreement?
- [+] Have you verified your asciidoc markup is correct?
=> Remove the company I'v added.

content/community/user_groups.adoc
=> added London Clojurians community links

content/guides/deps_and_cli.adoc
=> Whitespace change - fix indentation in prep-lib example

content/guides/tools_build.adoc
=> Fix indentation in tools.build guide

content/reference/java_interop.adoc
- [y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [y] Have you signed the Clojure Contributor Agreement?
- [y] Have you verified your asciidoc markup is correct?
=> Correct namespace/path for clojure.xml

content/community/resources.adoc
Recently twitter released the feature of creating a community for my profile, I took the liberty of creating one in the name of Clojure
> for the maintainers of the clojure language who want to help moderating send DM that I add as moderator
=> twitter community

content/community/resources.adoc
=> Add cljdoc to community resources

content/guides/repl/enhancing_your_repl_workflow.adoc
=> Fix broken link

content/community/companies.adoc
Mobot tests mobile apps using mechanical robots.  The majority of our system is written in Clojure.
=> Add Mobot to the list of companies using Clojure

content/api/cheatsheet.html
- [Y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
=> Update cheatsheet to v53 with some new Vars from Clojure 1.11

content/guides/repl/enhancing_your_repl_workflow.adoc
Motivated by: https://www.lambdasierra.com/2022/hello
=> Name change: Stuart -> Alessandra Sierra in REPL guide

content/community/companies.adoc
=> Add Whimsical to companies list

content/community/companies.adoc
=> Add greenlabs to companies list

content/community/companies.adoc
=> Add Gaiwan to company list

content/events/2022/clojurebridge-london-sept-2022.adoc
=> New Event - ClojureBridge London Sept 2022

content/community/companies.adoc
=> Add Treasury Prime to companies list

content/community/companies.adoc
=> Added Roam Research to companies list

content/community/companies.adoc
=> adding Redefine.io to the companies list

content/community/resources.adoc
=> Add new video course "Clojure Hacker" to resources

content/guides/deps_and_cli.adoc, content/reference/deps_and_cli.adoc
Examples of input and output are good in general, and I hope that this will help others in the future.
=> Add examples for deps.edn sources options

content/community/companies.adoc
=> Add Composer.Trade to companies list

content/community/training.adoc
=> Add available courses and clojure.stream

content/community/resources.adoc
aka [clj.social](https://clj.social)
=> add clojure community on fediverse

content/reference/java_interop.adoc
Provide a simple explanation of how it may be used.
-=david=-
=> Add in missing ^objects type alias

content/community/companies.adoc
=> Add Hummi to companies.adoc

content/news/2022/12/22/deref.adoc
=> Remove duplicate 2022/12/22 deref

content/guides/faq.adoc
Per https://ask.clojure.org/index.php/11417/invoke-clojure-with-an-argument?show=12583#c12583
=> Clarify how to pass --illegal-access flag

content/community/companies.adoc
=> Add Scrintal to companies.adoc

content/news/2023/02/26/deref.adoc
=> Add missing author for Enion Online

content/guides/editors.adoc
- [Y ] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
=> Update vim section of editors.adoc

content/guides/weird_characters.adoc
=> Refer to clj->js to recursively transform ClojureScript data

content/news/2023/04/14/deref.adoc
There were some audio issues with the previous video - have since re-uploaded a better version!
=> Edit deref link

content/guides/deps_and_cli.adoc
- checked: still in the list under `eval`
=> Correct typo in default gitlibs-path

content/news/2023/06/02/deref.adoc
=> Fix fulcro-rad link

content/community/companies.adoc
=> Add Belit to companies.adoc

content/community/tools.adoc
Add install guide section to Neovim and include link to Practicalli Neovim
Update link to Practicalli guide to spacemacs
=> community tools: Neovim guide from Practicalli

content/community/tools.adoc
=> Add FlowStorm to debuggers section of community tools.adoc

content/guides/learn/namespaces.adoc
=> Document use of :as-alias

content/community/companies.adoc
=> Remove Mixpanel from companies

content/reference/deps_and_cli.adoc
=> Fix type deps_and_cli.adoc: specfier

content/guides/weird_characters.adoc
See: https://ask.clojure.org/index.php/14004/add-example-to-namespaced-maps-for-foo-functionality
Example:
=> Add :_/foo example for namespaced maps

content/community/user_groups.adoc
The old meetup group is inactive since 2019.
=> Update Brazil meetup

content/community/user_groups.adoc
As announced on the [latest Meetup.com event](https://www.meetup.com/madison-clojure-meetup/events/304256369/?eventOrigin=group_upcoming_events) Madison Clojure has moved its website.
=> Update Madison Clojure website

content/community/companies.adoc
=> Add DIAS in companies list

content/community/resources.adoc
Signed-off-by: Sean Corfield <sean@corfield.org>
=> improve description of clojure-doc.org

content/reference/deps_edn.adoc
=> Fix deps.edn `:checksum` example value

content/guides/structural_editing.adoc
=> fix typos in structural editing page

content/guides/install_clojure.adoc
=> Fix typo in install_clojure.adoc
