content/community/resources.adoc

IRC is just the protocol, we need to specify which server(s).
p.s. CA is under "Maximilien Penet"

specify freenode.net IRC servers

---

content/api/api.adoc

At the moment the link  for cljs info end up redirecting to the cheatsheet.
So it's miss leading expecting an api and getting a document called cheatsheet

cljs api -> cljs cheatsheet

---

content/guides/getting_started.adoc

I think Boot has been around long enough and it is stable / powerful enough to warrant a mention right up there with Leiningen on the Getting Started page.

Add Boot to Clojure Tools

---

content/guides/getting_started.adoc

Maybe it would fit better under "Video training", but it's not "(commercial)", so I placed it under "Community" instead. Hope you think it worthy of inclusion.

Add Parens of the Dead to the Guides section

---

content/reference/java_interop.adoc

The formatting was wrong on the java-example, as it was annotated as clojure source

corrects source type on java example

---

content/reference/special_forms.adoc

`applies to to defn` -> `applies to defn`

Fix typo in special_forms

---

content/reference/transients.adoc

This change fixes a typo.
Note (I've tried this twice): I am replacing a single `)` with a space ` ` on line 65, but the GitHub UI seems to think I'm also making a non-change on line 92. (It must be whitespace I can't see.)

Fix typo extra paren transients example

---

content/guides/spec.adoc

`instrument` is missing the spec namespace alias

Update spec.adoc to add namespace to `instrument`

---

content/guides/spec.adoc

`double?` isn't a function on clojure.core so it will be undefined if someone is simply following the instructions. Since the example doesn't rely on the number being strictly a `Double` this change won't cause harm.

Update spec.adoc to replace double? with float?

---

content/guides/spec.adoc

typo fix for spec.adoc

---

content/guides/spec.adoc

On alpha5 I'm not even getting the "spec: $specname" part, but I guess this will be fixed in the future?

Fix spec names in example output.

---

content/guides/spec.adoc

No need to define it here, gives a warning.

boolean? is now part of clojure.core

---

content/reference/reader.adoc

The following link navigates you to the ToC bar instead of the header itself:
http://clojure.org/reference/reader#syntax-quote
The asciidoc syntax for explicit section ids was just slightly off.

fix syntax-quote header in reader.adoc

---

content/reference/evaluation.adoc

It is referring to function definitions as an example, but i.e. is not appropriate.
Included let forms in the example to make it consistent with the "(e.g. a function argument or let-bound name)" that follows.

Change i.e. -> e.g. and also mention let

---

content/reference/java_interop.adoc

Fix for issue "java arrays aliases hard to understand #132"

Make Java array aliases section a little easier to understand

---

content/guides/spec.adoc

Asciidoc converts '<=' (less-equal) into a left facing arrow. Solution is to escape the '<' char.

Small typo

---

content/guides/spec.adoc

The #:: conflicts with asciidoc.

Use backticks on namespace literal syntax

---

content/reference/protocols.adoc

For an example, e.g. should be used
Before: i.e. given a protocol my.ns/Protocol, an interface my.ns.Protocol.
After: e.g. given a protocol my.ns/Protocol, an interface my.ns.Protocol.

Change i.e. -> e.g.

---

content/about/spec.adoc

Really feels like there should be a period here.
Feel free to discard if you think this is too trivial, it's just something that bothered me when I was reading the document :)

Extremely small copy tweak to /about/spec

---

content/events/2016/clojurebridge_minneapolis.adoc
content/events/2016/clojurebridge_sanfrancisco.adoc

I'd like to add two ClojureBridge workshops scheduled recently, Minneapolis, MN and San Francisco, CA.

adds clojurebridge minneapolis and san francisco workshops

---

content/guides/spec.adoc

This makes it easier to distinguish the output from a code snippet

Comment out s/explain result in card game example

---

content/events/2016/clojurebridge_berlin_2.adoc
content/events/2016/clojurebridge_london_3.adoc

ClojureBridge London and Berlin are scheduled on Nov 25-26. Please add these two in upcoming events section.

Adds ClojureBridge London and Berlin

---

content/events/2017/clojurebridge-ba.adoc

ClojureBridge Buenos Aires is scheduled for March 10th & 11th. More info: http://bridge.clojureba.com. It would be great to have it listed in the events section :)

Adds ClojureBridge Buenos Aires

---

content/guides/spec.adoc

When following the guide using the current version of Clojure (`1.9.0-alpha14`) I get different explain output to what the guide presents.
When evaluating:
```clojure
(def email-regex #"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,63}$")
(s/def ::email-type (s/and string? #(re-matches email-regex %)))
(s/def ::acctid int?)
(s/def ::first-name string?)
(s/def ::last-name string?)
(s/def ::email ::email-type)
(s/def ::person (s/keys :req [::first-name ::last-name ::email] :opt [::phone]))
(s/explain ::person  {::first-name "Elon"})
```
Rather than a single message with a combined predicate:
```
val: #:my.domain{:first-name "Elon"} fails spec: :my.domain/person predicate: [(contains? % :my.domain/last-name) (contains? % :my.domain/email)]
```
I get one message, and predicate, per missing …

Spec Guide: Correct explain output for keys spec failure

---

content/guides/spec.adoc

The explain output for failed attribute conformance in a `keys` spec seems to be incorrect.
Rather than:
```clj
(s/explain ::person
{::first-name "Elon"
::last-name "Musk"
::email "n/a"})
;; In: [:my.domain/email] val: "n/a" fails spec: :my.domain/email
;;   at: [:my.domain/email] predicate: (re-matches email-regex %)
```
On Clojure `1.9.0-alpha14` I get:
```clj
;; In: [:my.domain/email] val: "n/a" fails spec: :my.domain/email-type
;;   at: [:my.domain/email] predicate: (re-matches email-regex %)
```
Explain seems to be using the 'root' spec's name rather than the immediate spec referenced in `s/keys`.

Spec Guide: Correct spec name used in explain output

---

content/guides/spec.adoc

On success, in Clojure `1.9.0-alpha14`, `(stest/check)` returns a map with `(:spec :clojure.spec.test.check/ret :sym)` keys. It doesn't have a `:result` key.
Also, the default `num-tests` is now `[1000](https://github.com/clojure/clojure/blob/c0326d2386dd1227f35f46f1c75a8f87e2e93076/src/clj/clojure/spec/test.clj#L304)`, not `100`.

Spec Guide: Fix stest/check success return value

---

content/reference/multimethods.adoc

The comment about parents and ancestors relates to class relationships and not to vectors.

Reorder the comment about parents and ancestors

---

content/reference/reader.adoc

`data_readers.clj` is monospace in references before and after this one. This change brings the regular-text reference in line with the others for consistency and clarity.

Code-ify reference to data_readers.clj

---

content/guides/spec.adoc

It seems that, without escaping, both # characters disappear. Adding a
single backslash to the first # also fixes the second....

Escape sharp character

---

content/guides/weird_characters.adoc

Unnecessary and po4a fails to parse it, making it an obstacle for translation

Remove extraneous '[]'

---

content/reference/repl_and_main.adoc

Rather not translate quoted code blocks because they mean the literal output from the actual program.
Most of the time they can be left untranslated, but this one has info worth translating.
Promote the info in the quoted block to actual content
- i18n the usage message in clojure itself (do not see it happening)

Promote usage snippet to content

---

content/reference/repl_and_main.adoc

- Labelling shell interactions as clojure code could be a bit confusing
- Apparently 'clojure-repl' is valid in highlight,js

Update language for the code section

---

content/events/2017/clojurebridge-sanfrancisco.adoc

So we're hosting ClojureBridge in SF on 09/16/17!
Here is the link to eventbrite: https://www.eventbrite.com/e/clojurebridge-intro-to-programming-workshop-tickets-36278581213
Link to ClojureBridge Workshop PR: https://github.com/ClojureBridge/Workshops/issues/61

add ClojureBridge SF 09/16/17 event

---

content/events/2017/clojurebridge-sanfrancisco.adoc

SF Clojurebridge 2017 link is created per https://github.com/ClojureBridge/Workshops/issues/61#issuecomment-319347795. This PR is to conform the URL to http://www.clojurebridge.org/events/2017-09-15-san-francisco

Update clojurebridge sf 2017 url

---

content/reference/special_forms.adoc

I had a hard time telling what part of this was the destructuring form and what part was the data, because they are were on different lines. I  modified this example to better match the previous examples with the `m` binding on a previous line in the `let`.

Make long destructuring example more clear

---

content/guides/learn/hashed_colls.adoc

Tiny one-character typo fix. 
Fixes #224

Correct "kewyord" typo in Hashed Collections guide

---

content/reference/java_interop.adoc

This change adds a brief description of primitive type hinting
capabilities in function arguments and return type.
This information does not seem to be documented in the reference. I
believe it should be – I had to dig around a little in the compiler and
generated code and would like to make this information easier to find.

Document support for primitive function arguments and return type

---

content/reference/special_forms.adoc

This PR modifies the Special Forms reference docs per #221 to use `monospace` to denote words that are names from the arglist, Clojure core functions, or Java classes. This notation is described after some brief words describing special forms (using verbiage from elsewhere on clojure.org) at the top of the document.
Original use of emphasis and strong tags was maintained. Proofread with JBlake v2.5.0-SNAPSHOT.

Monospace names for arglist names

---

content/reference/deps_and_cli.adoc

Minor, and arguably this should be "AWS Maven Wagon", but "aws-maven" is the name of the repo as well as its Maven artifactId.

Fix misspelling of aws-maven project

---

content/reference/java_interop.adoc

To an experienced Clojure user it is clear that `(defn hinted-single ^String [])` is equivalent to `(defn hinted-single (^String []))` but it isn't so obvious to somebody less experienced, especially one used to the fact that function and type declaration is "magic" and not simply a reuse of mechanisms used in user code (namely metadata and metadata reader macro). So providing an explicit example will help them a lot to relate it to their code (that rarely uses multiple arities).

Explicit example of 1-arity return type hint

---

content/guides/repl/enhancing_your_repl_workflow.adoc
content/guides/repl/guidelines_for_repl_aided_development.adoc
content/guides/repl/introduction.adoc

The guide has mostly been about techniques and tools, this one is about more strategic thinking, something that has been emphasized a lot by Rich Hickey and Stuart Halloway in various presentations.
**Preview:** https://5ad1f40867610c5e46c4050c--clojure-site-preview-vvvvalvalval.netlify.com/guides/repl/guidelines_for_repl_aided_development
Since this change adds a new page, it also requires a change to the theme:
[theme-patch.txt](https://github.com/clojure/clojure-site/files/1910369/theme-patch.txt)

Added a 'Guidelines for REPL-Aided development' chapter to the REPL guide

---

content/guides/learn/functions.adoc

This adds an extra space between the exercise text and the bulleted list items. Without it, they aren't rendered as list items, but just plain text as part of the previous line.

Fix bullet list formatting in Learn Functions exercises 10 and 12

---

content/guides/repl/enhancing_your_repl_workflow.adoc

It's now part of the clojure-emacs GitHub org. I also took the liberty to cleanup all the trailing whitespace in the document, but I can remove this if you want.

Update the link to sayid

---

content/reference/transients.adoc

The summary says "Thread isolation - enforced" while a note above it says "That check was removed in 1.7 to ..." so thread isolation is no longer enforced.

"Thread isolation level" in transients' summary

---

content/guides/faq.adoc

Link sequential destructuring and update example.
It isn't a significant or really important change by any means, I just felt that perhaps the updated example demonstrates a more common usecase. Also added a link to the relevant guide for clarity in case the reader is not familiar with this method of destructuring.

update FAQ entry about underscores

---

content/guides/higher_order_functions.adoc

The article referred to a previous function 'rock-band?', but that doesn't exist. Neither existed 'bands' variable. I've searched for it on the internet, but the original article must have been lost. Hence this change makes the example complete.

Clarified example with 'rock-band' fiunction; two typos.

---

content/guides/getting_started.adoc

Whilst they are both linked in the Build Tools section at the bottom of the page, Windows users might not read that far. Linking them where they are mentioned in the Windows section will make it easier for Windows beginners to navigate to the appropriate tools, until the PowerShell version of the CLI tools is available.

Link Leiningen and Boot in the Windows section

---

content/guides/equality.adoc

- [Y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
This PR addresses all of the things I mentioned in this issue https://github.com/clojure/clojure-site/issues/334 except for the last one, which Alex suggested not bothering with.
It also fixes up some asciidoc formatting problems with many occurrences of ##NaN that were causing incorrect HTML that left out the ## symbols, and some bad asciidoc markup near the end in a sentence mentioning `EGAL`

Updates to Equality guide

---

content/reference/special_forms.adoc

The object thrown by `:pre` and `:post` conditions is not a subclass of Exception, it's an Error, and thus will not be caught with the `try/catch Exception` idiom. Update the docs to reflect this.

Pre conditions throw errors

---

content/about/rationale.adoc

There was some discussion about the Clojure website new user experience on Hacker News about 24 hours ago, and so I went to the "Getting Started" page to see what all the fuss was about. I ended up on the Overview page as the first link reading top-bottom left-right. The index page has a large green button labelled "Getting Started" that I skipped reading because it looked like a banner add and a prominent "Getting Started" button on the right hand side that looked like a "latest news" feed so I ignored it too. Some users, such as myself, are beyond hope.
Might someone please add a link to the Getting Started page at the end of the Rationale page? It seems like an extremely logical continuation.
- [ Yes] Have you read the [guidelines for …

Add link Rationale->Getting Started

---

content/guides/weird_characters.adoc

URL for macro's doc has prefix missing. Think this used to be the URL a while ago, but it doesn't redirect.

Fix broken link

---

content/news/2019/02/04/state-of-clojure-2019.adoc

This content can be accessed from two different ways:
1. https://clojure.org/news/news
2. https://clojure.org/news/2019/02/04/state-of-clojure-2019
When accessed from the first link, the links in the introduction are broken, producing a 404 error. They work in the second link, though. The fix makes sure the links work in both cases, making them relative.

Fixed links to anchors in the state of clojure 2019 news

---

content/guides/learn/functions.adoc

It turns out that when using http://www.w3.org/ the connection will
timeout, but when using https://www.w3.org/ results are as expected. I
can reproduce this using cURL, so it's not a Clojure thing, but still,
it could be frustrating to newbies to get an error while trying to
work on that exercise.

Update URL scheme on Functions doc

---

content/guides/core_async_go.adoc

it seems that a 2-arity func is being invoked with 1 arg
I think a channel needs to passed in... or, according to `put!` docs, a "port" (whatever that is :))

add missing argument

---

content/reference/deps_and_cli.adoc

This change adds documentation of Maven proxy settings to the deps and CLI reference.
See https://dev.clojure.org/jira/browse/TDEPS-20.

Document Maven proxy settings

---

content/events/2019/clojurebridge-london-may-2019.adoc

Adding to the Clojure.org events section the next ClojureBridge London event to
be held in May 2019.

New Event - ClojureBridge London May 2019

---

content/guides/learn/syntax.adoc

- [y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [y] Have you signed the Clojure Contributor Agreement?
- [y] Have you verified your asciidoc markup is correct?

Better markup for a few symbolic value occurrences

---

content/api/cheatsheet.html

Here is what I have already added that is new in Clojure 1.10:
Added to Namespace / From symbol section:
requiring-resolve
Added to Java Interoperation / Exceptions section:
ex-cause ex-message clojure.main/ex-str
And here are the new things in Clojure 1.10 that have not been added.
If someone would like them added to the cheatsheet, please recommend a
category (or multiple categories) to add them to, whether existing or
new.
PrintWriter-on
read+string
add-tap
remove-tap
tap>
clojure.core.protocols/Datafiable
clojure.core.protocols/Navigable
clojure.core.protocols/datafy
clojure.core.protocols/nav
clojure.core.server/io-prepl
clojure.core.server/prepl
clojure.core.server/remote-prepl
clojure.core.specs.alpha/even-number-of-forms?
clojure.spec.gen.alpha/shuffle
clojure.datafy/datafy …

Update cheatsheet for Clojure 1.10

---

content/guides/learn/functions.adoc

In the "Let" section, one of the "let" words isn't formatted correctly. My change is putting a "let" inside a pair of `.
- [y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [y] Have you signed the Clojure Contributor Agreement?
- [y] Have you verified your asciidoc markup is correct?

Conform a "let" word to asciidoc format

---

content/reference/deps_and_cli.adoc

Top level tag in the settings.xml has to be `<settings>` or Maven doesn't
read the options.

Fix Maven settings.xml example

---

content/community/contrib_libs.adoc

`clojure.java.jdbc` has no open issues at this point and I don't plan to do any further work on it (unless a blocking bug is found) as all of my future effort will go into `next.jdbc`.

Mark java.jdbc as Stable rather than Active

---

content/guides/destructuring.adoc

I struggled to find out how to use `:or` with namespaced keys. If you read the document thoroughly you will understand it but I think it is anyway better to provide a concrete example.

destructuring: `:or` and namespaced keys

---

content/events/2019/clojurex.adoc

Unfortunately the company that runs ClojureX conference in London is in financial administration.
- [ x] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [ x] Have you signed the Clojure Contributor Agreement?
- [ x] Have you verified your asciidoc markup is correct?

Notification of ClojureX 2019 cancellation

---

content/guides/learn/flow.adoc

In this way the sentences make more sense.
- [:heavy_check_mark:] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [:heavy_check_mark:] Have you signed the Clojure Contributor Agreement?
- [:heavy_check_mark:] Have you verified your asciidoc markup is correct?

fix some error

---

content/community/companies.adoc

Altometrics is now defunct. I should know; I was a co-founder.

Remove Altometrics from companies list

---

content/community/downloads.adoc

For someone completely new to Clojure, it's reasonable that most people will click on the large Get Started button, but a few people will still click on Releases and then the second link on the Releases page takes you to straight to the Maven repo, which is relevant for developers with experience with Maven or aware of the spec deps in Clojure 1.10.
Since there's still old pages and blogs that mention you can download a single Clojure jar ("it's just another Jar"), this hurts their fix experience into the language, because java -jar clojure-1.10.0.jar throws an Exception they cannot decipher.
All that the Releases page needs is a banner that warns people that if you are new to the language, go to the Getting Started page. I've also added a small entry to make more explicit that the …

Make more explicit that Clojure 1.10 needs spec deps at runtime

---

README.adoc

The jbake install link redirects, so passing -L is necessary in order
for curl to follow the redirect.

Fix jbake install instructions

---

content/community/resources.adoc

I've updated the recommended plugins/extensions for Atom, to Chlorine, and for VS Code, to Calva. In the latter case I am quite biased, but as [this question](https://github.com/avli/clojureVSCode/issues/113) suggests, `clojureVSCode` does not fully qualify the expectations for an editor integration as they are expressed on this page. Calva does, however.

Update recommendations for VS Code and Atom

---

content/guides/repl/enhancing_your_repl_workflow.adoc

page http://clojure-emacs.github.io/sayid/ is 404 now, replace to https://github.com/clojure-emacs/sayid

Fix link to 404 at enhancing_your_repl_workflow

---

content/guides/getting_started.adoc

a small change correcting a typo. 
"executales" -> "executables"

'executables' spelling correction

---

content/guides/repl/data_visualization_at_the_repl.adoc

Replace pevious with previous.
- [✓] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [✓] Have you signed the Clojure Contributor Agreement?
- [✓] Have you verified your asciidoc markup is correct?

Fix typo in data_visualization_at_the_repl.adoc

---

content/guides/deps_and_cli.adoc

The 'socket_repl' link was missing in the list of links at the begging of the section.

Added missing link in 'Other examples section'

---

content/guides/repl/basic_usage.adoc

Fixes small typo in guides/repl/basic_usage.

---

content/releases/tools.adoc

This branch has the same old releases, but also the newer 1.10.2.x releases.

Point "repo changelog" link at 1.10.2 branch

---

content/community/resources.adoc

Right now, the link is to clojurians.net which used to be the "inviter app" but was changed to just redirect to a join-Slack invitation link (because Slack changed how invitations worked). Unfortunately, that link has expired and the Clojurians Admin team do not have access to clojurians.net to change the link to a new one.
So I'm proposing changing the link on clojure.org to directly be a new invitation link -- it should not expire until 2,000 people have used it (in theory) -- and once we get control of clojurians.net again, I'll submit a PR to change this page back to clojurians.net. I'll also keep an eye on signups and if it looks like this new link will "run out", I'll get a new one created and submit another PR.
Sorry for the churn but we're out of options for the time being since …

Update Clojurians Slack link

---

content/community/resources.adoc

The Admin team now own the domain and have full access to it, and have it redirecting to a new Slack signup link.

Clojurians Slack Chat link -> clojurians.net

---

content/community/user_groups.adoc

Change Clojure Korea link in User Groups.

Update Clojure Korea Link

---

content/news/2021/03/18/apis-serving-people-and-programs.adoc

A couple of people have been confused by the current wording on Slack: I believe the intent was to say that `destr` "takes a sequence _of_ optional keyword arguments" (not _and_).

Fix typo: change 'and' to 'of'

---

content/about/spec.adoc

After a brief discussion on Clojurians, we decided to add some Presentations, Podcasts, and Blog Posts about Spec.

Add Presentations, Podcasts and Blog Posts to About Spec

---

content/community/resources.adoc

Upon joining #clojure on Freenode, ChanServ sends the following message:
> @ChanServ: [#clojure] This channel is moving to #clojure on irc.libera.chat
Seems proper to point the website to Libera channel as well.
Background on the move: 
- https://mastodon.sdf.org/@kline/106299403921451814
- https://lwn.net/Articles/856543/

IRC channel moved from Freenode to Libera

---

content/reference/transducers.adoc

Since `partition` doesn't have a transducer arity, I assume a better example is `partition-all`.

Fix ref to non-existent partition transducer

---

content/reference/deps_and_cli.adoc

Based on https://github.com/clojure/tools.deps.alpha/blob/655ea0a037f041e365cc56db0dc8181268c29998/src/main/clojure/clojure/tools/deps/alpha/extensions/git.clj#L19

Fix gitlab lib to url conventions

---

content/community/resources.adoc
content/events/2021/reclojure.adoc

Also remove skillsmatter, as this conference no longer exists.
Remove also 4clojure.com, as this service is deprecated (and the website
gives a security warning).
-=david=-

Add in re:Clojure 2021

---

content/guides/equality.adoc

Change mention of hash inconsistency for VecSeq objects as historical,
since it was fixed in Clojure 1.10.2.
- [Y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?

Minor updates to equality guide

---

content/guides/comparators.adoc

Also add a link to the clj-arrangement public library, which might be
useful for a Clojure developer wanting a comparator that works across
more types of values than Clojure's `compare`.
- [Y] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?

Add mention of new function NaN? in comparators guide

---

content/guides/learn/namespaces.adoc

I was puzzled that `:require` was referred to as a "class", then saw that in the following section, `:import` is called a "clause".
> the ns macro has an :import clause
I believe that the author meant to say "clause" above as well. 
Thanks!

:require class -> :require clause

---

content/community/start_group.adoc

Wikispaces is not functioning anymore since 2018.
https://helpiewp.com/wikispaces/

Remove wikispaces from the tools section

---

content/news/2022/06/24/deref.adoc

Made the link go to the main page as it has a better overview + demonstration video
Also makes the URL a bit prettier on the deployed website :)

Adjust link to Obsidian Wielder

---

content/reference/deps_and_cli.adoc

Fixes the following formatting issue:

Add newline to fix formatting in deps_and_cli.adoc

---

content/reference/macros.adoc

`(macroexpand '(-> {} (assoc :a 1) (assoc :b 2)))` actually produces `(assoc (assoc {} :a 1) :b 2)` (which is also what makes sense from the text description).

Update macros.adoc: fix typo in example output

---

content/guides/deps_and_cli.adoc

The single-segment namespace `java-time` has been softly deprecated due to https://github.com/dm3/clojure.java-time/issues/91
It has been duplicated to `java-time.api` in `1.1.0`.
I tried both the `find-versions` tool and repl call and updated the tutorial with the new results. I did not try the full tutorial, I stopped before needing to create a GitHub repo for `time-hello`.

Update java-time example

---

content/about/clojureclr.adoc

Replaced with the getting started guide, which includes instructions for getting the binaries.

Fix broken link in ClojureCLR page

---

content/community/tools.adoc

Since clojure-doc.org was resurrected as GitHub pages, the URLs changed and this link was broken. Since the Emacs page on clojure-doc.org is going away and I already submitted a PR for the editors page on clojure.org, I think it makes sense to just remove this old link instead of trying to replace it with something else.

Remove broken clojure-doc.org link

---

content/guides/editors.adoc

The Emacs page on clojure-doc.org is very outdated and is going to be retired. I propose linking to the official download/install page as a replacement.

Replace link to very outdated clojure-doc.org page

---

content/guides/repl/launching_a_basic_repl.adoc

"Other ways to run Clojure" was removed from [the getting started guide](https://github.com/clojure/clojure-site/blob/master/content/guides/getting_started.adoc) in 3ed1287c38d0edad6185728a796a48d809e29005

Remove broken link from repl guide

---

content/community/license.adoc

Link now points to correct OSI page for EPL-1.0, previously resulted in page-not-found.
Out of interest, does anyone know why Clojure has not updated to EPL v2.0? Might be worth putting a teeny-tiny FAQ on this page.

Fix broken EPL-1.0 link in license.adoc

---

content/community/tools.adoc

Emacs
- simplify the Cider description
- add clojure-ts-mode (new project under development)
- add CIDER getting started guide
- add Corgi distribution
Visual Studio Code
- add calva get started guide
- add VSpaceCode configuration
Neovim
- astronvim distribution and astrocommunity Clojure pack
- Magic-kit distribution (Conjure maintainer)
- cajus-nfnl distribution
Pulsar
- add pulsar editor and link to clojure related packages
- add Chlorine link (GitLab project)
Inactive editor projects
- move inactive editors to separate section for simpler reference
- Lighttable linked to GitHub repository (main website not available)
Table of contents added

community: update editor project links on tools page

---

content/guides/dev_startup_time.adoc

It wasn't clear to me at all that compile only happens when loading a ns for the first time / force reloading it. HereI try to clarify this for the next person.

Clarify dev_startup_time w.r.t. already required nss

---

content/reference/java_interop.adoc

here we are speaking of the parameters to a function not the arguments in an invocation

Update java_interop.adoc arguments -> parameters

---

content/guides/install_clojure.adoc

When following this guide today I got back the following errors: 
```
brew tap homebrew/cask-versions
Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```
and then 
```
brew install --cask temurin21
Warning: Cask 'temurin21' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
==> Casks
temurin               temurin@11            temurin@17            temurin@19            temurin@20            temurin@21            temurin@8
```
pointing to `temurin@21` works, hence that change

remove empty cask, use temurin[at]21

---

content/community/companies.adoc

Our company DocSolver was renamed to Basil Inc, as can be seen at https://docsolver.com.

Rename DocSolver to Basil Inc in companies.adoc

---

content/reference/data_structures.adoc

Typo / grammar

---

content/guides/tools_build.adoc

The form `path roots` appears twice in this sentence, with two different spellings. I believe they should be spelled the same way, and the first one is correct (singular `path` with multiple `roots`). Happy to switch the change if the latter assumption is incorrect.

tools_build: inconsistent spelling of "path[s] roots"

---

content/news/2021/06/11/deref.adoc
content/news/2021/06/25/deref.adoc
content/news/2021/10/08/deref.adoc
content/news/2022/05/27/deref.adoc
content/news/2022/09/09/deref.adoc
content/news/2023/11/10/deref.adoc
content/news/2023/11/17/deref.adoc
content/news/2023/12/08/deref.adoc
content/news/2024/02/02/deref.adoc
content/news/2024/02/26/deref.adoc
content/news/2024/06/01/deref.adoc
content/news/2024/07/17/deref.adoc
content/news/2024/10/11/deref.adoc
content/news/2025/06/27/deref.adoc

(**jbake <2.7.0-rc.7 doesn't seem to run on Apple Silicon chips. I would be grateful if someone could check that everything renders correctly.**)
The latest Deref (and others) contains links with `--`. Asciidoctor substitutes these with an em dash (`%E2%80%94`) and a zero-width space (`%E2%80%8B`) (see [their docs](https://docs.asciidoctor.org/asciidoc/latest/subs/replacements/) for all substitutions). 
This breaks many URLs. (Interestingly, spotify.com seems fine with that.)
---
Original URL: 
`https://yamlscript.org/blog/2025-06-27/fun-fridays--rosetta-code/`
The resulting URL looks like this:
`https://yamlscript.org/blog/2025-06-27/fun-fridays%E2%80%94%E2%80%8Brosetta-code/`
This can be prevented by writing:
`link:++https://yamlscript.org/blog/2025-06-27/fun-fridays--rosetta-code/++` …

Escape all URLs containing `--` and `'`

---

content/dev/contrib_libs.adoc

It has been marked Stable for a long time and has had no releases in well over four years, so Inactive is more accurate.
I also want to "encourage" folks to choose `next.jdbc` instead of `java.jdbc` at this point, and the README has labeled `java.jdbc` as "Inactive" and recommended `next.jdbc` for some time.

Change java.jdbc status to Inactive
